// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.20.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> colorBoxNew({required int actorId, dynamic hint}) =>
    RustLib.instance.api.colorBoxNew(actorId: actorId, hint: hint);

Future<void> colorBoxDelete({required int actorId, dynamic hint}) =>
    RustLib.instance.api.colorBoxDelete(actorId: actorId, hint: hint);

Future<ColorModel?> colorBoxChangeColor({required int actorId, dynamic hint}) =>
    RustLib.instance.api.colorBoxChangeColor(actorId: actorId, hint: hint);

Stream<ColorModel> colorBoxChangeColorSink(
        {required int actorId, dynamic hint}) =>
    RustLib.instance.api.colorBoxChangeColorSink(actorId: actorId, hint: hint);

Future<void> colorBoxCancelChangeColorSink(
        {required int actorId, dynamic hint}) =>
    RustLib.instance.api
        .colorBoxCancelChangeColorSink(actorId: actorId, hint: hint);

Future<String?> colorBoxLike({required int actorId, dynamic hint}) =>
    RustLib.instance.api.colorBoxLike(actorId: actorId, hint: hint);

class ColorModel {
  final int red;
  final int green;
  final int blue;

  const ColorModel({
    required this.red,
    required this.green,
    required this.blue,
  });

  String description({dynamic hint}) =>
      RustLib.instance.api.colorModelDescription(
        that: this,
      );

  @override
  int get hashCode => red.hashCode ^ green.hashCode ^ blue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColorModel &&
          runtimeType == other.runtimeType &&
          red == other.red &&
          green == other.green &&
          blue == other.blue;
}
