// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.22.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::rust_async::RwLock<User>>
@sealed
class User extends RustOpaque {
  User.dcoDecode(List<dynamic> wire) : super.dcoDecode(wire, _kStaticData);

  User.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_User,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_User,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_UserPtr,
  );

  static Future<User> newUser({required int id, dynamic hint}) =>
      RustLib.instance.api.userNew(id: id, hint: hint);
}
